### ISSUE TITLE
Remove project stale branches

### ISSUE THREAD

**Issue by acuarica** [renpool/renpool-contracts#1]
The repo was configured to **not** `Automatically delete head branches`[1] after pull requests are merged.

Review current project branches to check whether they have become stale. If so, we should delete them.

List of all branches https://github.com/renpool/renpool-contracts/branches/all

---

[1] https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by acuarica** [comment]
The following branches have no commits ahead of `main`. It should be safe to delete them.

```
rel/brownie
fea/ethersjs
fea/fe-tests
```

**Comment by acuarica** [comment]
The branch `cancelWithdrawRequest` seems to be already included in #29. It should be safe to delete it.

**Comment by acuarica** [comment]
The rest of the branches should have a corresponding PR.

@fede-rodes to keep in the loop.

**Comment by fede-rodes** [comment]
We can remove all mentioned branches, in case of need we can have a look at the old repo

**Comment by acuarica** [comment]
The mentioned branches 

```
rel/brownie
fea/ethersjs
fea/fe-tests
cancelWithdrawRequest
```

were deleted.

**Comment by acuarica** [comment]
The only remaining branches coming from the old repo are

```
fea/56-fede
fea/fe-gateway
```

@fede-rodes what should we do with them?

**Comment by acuarica** [comment]
Branches were deleted, thanks!!
